CREATE DATABASE IF NOT EXISTS cloudsphere_db CHARACTER SET utf8mb4; USE cloudsphere_db;
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),email VARCHAR(150) UNIQUE,password VARCHAR(255) NOT NULL,role VARCHAR(30),status VARCHAR(20),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE services(id INT AUTO_INCREMENT PRIMARY KEY,service_name VARCHAR(120),service_type VARCHAR(80),provider VARCHAR(80),status VARCHAR(20),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE servers(id INT AUTO_INCREMENT PRIMARY KEY,server_name VARCHAR(120),operating_system VARCHAR(80),cpu VARCHAR(30),ram VARCHAR(30),storage VARCHAR(30),ip_address VARCHAR(45),status VARCHAR(20),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE storage_resources(id INT AUTO_INCREMENT PRIMARY KEY,storage_name VARCHAR(120),storage_type VARCHAR(80),capacity VARCHAR(30),used_space VARCHAR(30),available_space VARCHAR(30),status VARCHAR(20),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE cloud_databases(id INT AUTO_INCREMENT PRIMARY KEY,database_name VARCHAR(120),database_engine VARCHAR(80),storage VARCHAR(30),status VARCHAR(20),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE usage_logs(id INT AUTO_INCREMENT PRIMARY KEY,resource_type VARCHAR(80),resource_name VARCHAR(120),usage_value DECIMAL(5,2),usage_date DATE);
INSERT INTO users(name,email,password,role,status) VALUES
('Cloud Administrator','admin@cloudsphere.com','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.','Admin','Active'),('Cloud User 2','user2@cloudsphere.local','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.','User','Active'),('Cloud User 3','user3@cloudsphere.local','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.','Manager','Active'),('Cloud User 4','user4@cloudsphere.local','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.','User','Active'),('Cloud User 5','user5@cloudsphere.local','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.','User','Active'),('Cloud User 6','user6@cloudsphere.local','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.','Manager','Active'),('Cloud User 7','user7@cloudsphere.local','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.','User','Active'),('Cloud User 8','user8@cloudsphere.local','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.','User','Active'),('Cloud User 9','user9@cloudsphere.local','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.','Manager','Active'),('Cloud User 10','user10@cloudsphere.local','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.','User','Active');
INSERT INTO services(service_name,service_type,provider,status) VALUES ('Cloud Service 1','Storage','CloudSphere','Active');
INSERT INTO services(service_name,service_type,provider,status) VALUES ('Cloud Service 2','Database','CloudSphere','Active');
INSERT INTO services(service_name,service_type,provider,status) VALUES ('Cloud Service 3','Backup','CloudSphere','Active');
INSERT INTO services(service_name,service_type,provider,status) VALUES ('Cloud Service 4','Networking','CloudSphere','Maintenance');
INSERT INTO services(service_name,service_type,provider,status) VALUES ('Cloud Service 5','Compute','CloudSphere','Active');
INSERT INTO services(service_name,service_type,provider,status) VALUES ('Cloud Service 6','Storage','CloudSphere','Active');
INSERT INTO services(service_name,service_type,provider,status) VALUES ('Cloud Service 7','Database','CloudSphere','Active');
INSERT INTO services(service_name,service_type,provider,status) VALUES ('Cloud Service 8','Backup','CloudSphere','Maintenance');
INSERT INTO services(service_name,service_type,provider,status) VALUES ('Cloud Service 9','Networking','CloudSphere','Active');
INSERT INTO services(service_name,service_type,provider,status) VALUES ('Cloud Service 10','Compute','CloudSphere','Active');
INSERT INTO services(service_name,service_type,provider,status) VALUES ('Cloud Service 11','Storage','CloudSphere','Active');
INSERT INTO services(service_name,service_type,provider,status) VALUES ('Cloud Service 12','Database','CloudSphere','Maintenance');
INSERT INTO services(service_name,service_type,provider,status) VALUES ('Cloud Service 13','Backup','CloudSphere','Active');
INSERT INTO services(service_name,service_type,provider,status) VALUES ('Cloud Service 14','Networking','CloudSphere','Active');
INSERT INTO services(service_name,service_type,provider,status) VALUES ('Cloud Service 15','Compute','CloudSphere','Active');
INSERT INTO servers(server_name,operating_system,cpu,ram,storage,ip_address,status) VALUES ('Server-01','Linux','3 vCPU','8 GB','125 GB','10.0.0.1','Running');
INSERT INTO servers(server_name,operating_system,cpu,ram,storage,ip_address,status) VALUES ('Server-02','Windows Server','4 vCPU','12 GB','150 GB','10.0.0.2','Running');
INSERT INTO servers(server_name,operating_system,cpu,ram,storage,ip_address,status) VALUES ('Server-03','Linux','5 vCPU','16 GB','175 GB','10.0.0.3','Running');
INSERT INTO servers(server_name,operating_system,cpu,ram,storage,ip_address,status) VALUES ('Server-04','Windows Server','2 vCPU','4 GB','200 GB','10.0.0.4','Running');
INSERT INTO servers(server_name,operating_system,cpu,ram,storage,ip_address,status) VALUES ('Server-05','Linux','3 vCPU','8 GB','225 GB','10.0.0.5','Running');
INSERT INTO servers(server_name,operating_system,cpu,ram,storage,ip_address,status) VALUES ('Server-06','Windows Server','4 vCPU','12 GB','250 GB','10.0.0.6','Running');
INSERT INTO servers(server_name,operating_system,cpu,ram,storage,ip_address,status) VALUES ('Server-07','Linux','5 vCPU','16 GB','275 GB','10.0.0.7','Running');
INSERT INTO servers(server_name,operating_system,cpu,ram,storage,ip_address,status) VALUES ('Server-08','Windows Server','2 vCPU','4 GB','300 GB','10.0.0.8','Running');
INSERT INTO servers(server_name,operating_system,cpu,ram,storage,ip_address,status) VALUES ('Server-09','Linux','3 vCPU','8 GB','325 GB','10.0.0.9','Running');
INSERT INTO servers(server_name,operating_system,cpu,ram,storage,ip_address,status) VALUES ('Server-10','Windows Server','4 vCPU','12 GB','350 GB','10.0.0.10','Running');
INSERT INTO storage_resources(storage_name,storage_type,capacity,used_space,available_space,status) VALUES ('Storage-01','Object','600 GB','195 GB','405 GB','Active');
INSERT INTO storage_resources(storage_name,storage_type,capacity,used_space,available_space,status) VALUES ('Storage-02','Block','700 GB','240 GB','460 GB','Active');
INSERT INTO storage_resources(storage_name,storage_type,capacity,used_space,available_space,status) VALUES ('Storage-03','Object','800 GB','285 GB','515 GB','Active');
INSERT INTO storage_resources(storage_name,storage_type,capacity,used_space,available_space,status) VALUES ('Storage-04','Block','900 GB','330 GB','570 GB','Active');
INSERT INTO storage_resources(storage_name,storage_type,capacity,used_space,available_space,status) VALUES ('Storage-05','Object','1000 GB','375 GB','625 GB','Active');
INSERT INTO storage_resources(storage_name,storage_type,capacity,used_space,available_space,status) VALUES ('Storage-06','Block','1100 GB','420 GB','680 GB','Active');
INSERT INTO storage_resources(storage_name,storage_type,capacity,used_space,available_space,status) VALUES ('Storage-07','Object','1200 GB','465 GB','735 GB','Active');
INSERT INTO storage_resources(storage_name,storage_type,capacity,used_space,available_space,status) VALUES ('Storage-08','Block','1300 GB','510 GB','790 GB','Active');
INSERT INTO storage_resources(storage_name,storage_type,capacity,used_space,available_space,status) VALUES ('Storage-09','Object','1400 GB','555 GB','845 GB','Active');
INSERT INTO storage_resources(storage_name,storage_type,capacity,used_space,available_space,status) VALUES ('Storage-10','Block','1500 GB','600 GB','900 GB','Active');
INSERT INTO cloud_databases(database_name,database_engine,storage,status) VALUES ('Database-01','PostgreSQL','30 GB','Active');
INSERT INTO cloud_databases(database_name,database_engine,storage,status) VALUES ('Database-02','MongoDB','40 GB','Active');
INSERT INTO cloud_databases(database_name,database_engine,storage,status) VALUES ('Database-03','MariaDB','50 GB','Active');
INSERT INTO cloud_databases(database_name,database_engine,storage,status) VALUES ('Database-04','MySQL','60 GB','Active');
INSERT INTO cloud_databases(database_name,database_engine,storage,status) VALUES ('Database-05','PostgreSQL','70 GB','Active');
INSERT INTO cloud_databases(database_name,database_engine,storage,status) VALUES ('Database-06','MongoDB','80 GB','Active');
INSERT INTO cloud_databases(database_name,database_engine,storage,status) VALUES ('Database-07','MariaDB','90 GB','Active');
INSERT INTO cloud_databases(database_name,database_engine,storage,status) VALUES ('Database-08','MySQL','100 GB','Active');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Storage','Resource-2',42,'2026-09-02');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Database','Resource-3',49,'2026-09-03');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Backup','Resource-4',56,'2026-09-04');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Networking','Resource-5',63,'2026-09-05');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Compute','Resource-6',70,'2026-09-06');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Storage','Resource-7',77,'2026-09-07');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Database','Resource-8',84,'2026-09-08');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Backup','Resource-9',36,'2026-09-09');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Networking','Resource-10',43,'2026-09-10');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Compute','Resource-1',50,'2026-09-11');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Storage','Resource-2',57,'2026-09-12');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Database','Resource-3',64,'2026-09-13');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Backup','Resource-4',71,'2026-09-14');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Networking','Resource-5',78,'2026-09-15');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Compute','Resource-6',85,'2026-09-16');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Storage','Resource-7',37,'2026-09-17');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Database','Resource-8',44,'2026-09-18');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Backup','Resource-9',51,'2026-09-19');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Networking','Resource-10',58,'2026-09-20');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Compute','Resource-1',65,'2026-09-21');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Storage','Resource-2',72,'2026-09-22');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Database','Resource-3',79,'2026-09-23');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Backup','Resource-4',86,'2026-09-24');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Networking','Resource-5',38,'2026-09-25');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Compute','Resource-6',45,'2026-09-26');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Storage','Resource-7',52,'2026-09-27');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Database','Resource-8',59,'2026-09-28');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Backup','Resource-9',66,'2026-09-01');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Networking','Resource-10',73,'2026-09-02');
INSERT INTO usage_logs(resource_type,resource_name,usage_value,usage_date) VALUES ('Compute','Resource-1',80,'2026-09-03');
